name: |-
  Controller - Create Release branch
  
  Create `release/{version}` branch for the release 

  ### Usage 

  ```yaml
    name: Main branch
    on:
      release:
        types: [published]

    jobs:
      do:
        uses: ./.github/workflows/workflow-controller-hotfix-release-branch.yml
        with:
          version: $\{\{ github.event.release.tag_name \}\}
  ```  

on:
  workflow_call:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  release-branch:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create branch for specific version
        uses: satya-500/create-branch-from-tag@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          branch: release/${{ inputs.version }}
          from: tags/${{ inputs.version }}

